import { StyleSheet } from 'react-native';

export const splashScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 24,
    backgroundColor: '#0D0D0D',
  },
  lensField: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0D0D0D',
  },
  lensPlane: {
    position: 'absolute',
    left: '-28%',
    width: '156%',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#1E1E1E',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
  },
  lensPlaneA: {
    top: '20%',
    height: 112,
    backgroundColor: '#1A1A1A',
  },
  lensPlaneB: {
    top: '38%',
    height: 156,
    backgroundColor: '#111111',
  },
  lensPlaneC: {
    top: '59%',
    height: 98,
    backgroundColor: '#161616',
  },
  lockup: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  chip: {
    width: 108,
    height: 108,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
    borderWidth: 1,
    borderColor: '#FF6B35',
    borderRadius: 30,
    backgroundColor: '#111111',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.32,
    shadowRadius: 28,
  },
  chipText: {
    fontFamily: 'Anton',
    fontSize: 38,
    lineHeight: 48,
    color: '#FF6B35',
    letterSpacing: 1.2,
  },
  copy: {
    alignItems: 'center',
  },
  eyebrow: {
    marginBottom: 10,
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#888888',
    letterSpacing: 2.4,
  },
  title: {
    fontFamily: 'Anton',
    fontSize: 42,
    lineHeight: 52,
    color: '#FFFFFF',
    letterSpacing: 5.2,
  },
  readyPill: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 78,
    marginTop: 18,
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#FF6B35',
  },
  readyText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 1.8,
  },
});
