import { StyleSheet } from 'react-native';

export const splashScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 24,
    backgroundColor: '#0D0D0D',
  },
  lensField: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0D0D0D',
  },
  lensPlane: {
    position: 'absolute',
    left: '-24%',
    width: '148%',
    height: 96,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#1E1E1E',
    backgroundColor: '#1A1A1A',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
  },
  lockup: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  chip: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FF6B3588',
    borderRadius: 30,
    backgroundColor: '#111111',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 34,
  },
  chipText: {
    fontFamily: 'Anton',
    fontSize: 34,
    lineHeight: 44,
    color: '#FF6B35',
    letterSpacing: 1,
  },
  copy: {
    alignItems: 'center',
  },
  eyebrow: {
    marginBottom: 10,
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#888888',
    letterSpacing: 2.4,
  },
  title: {
    fontFamily: 'Anton',
    fontSize: 42,
    lineHeight: 42,
    color: '#FFFFFF',
    letterSpacing: 5,
  },
  readyPill: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 82,
    height: 30,
    marginTop: 12,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: '#FF6B35',
  },
  readyText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 1.4,
  },
});
