import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#0D0D0D' },
  nav: {
    height: 56,
    backgroundColor: '#0D0D0D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E1E',
  },
  navTitle: { fontFamily: 'Inter', fontSize: 17, fontWeight: '700', color: '#FFFFFF' },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#1A1A1A',
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusBadgeText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: '#FFFFFF',
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 20 },
  inputBar: {
    backgroundColor: '#0D0D0D',
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 34,
    gap: 8,
  },
  inputField: {
    flex: 1,
    minHeight: 52,
    maxHeight: 120,
    backgroundColor: '#1A1A1A',
    borderRadius: 26,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  inputDisabled: { opacity: 0.4 },
  input: { fontFamily: 'Inter', fontSize: 15, color: '#FFFFFF', minHeight: 20 },
  sendStopBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  sendBtn: { backgroundColor: '#FF6B35' },
  stopBtn: { backgroundColor: '#1A1A1A', borderWidth: 1, borderColor: '#FF4444' },
  previewRow: { backgroundColor: '#0D0D0D', maxHeight: 68 },
  previewRowContent: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  thumbWrapper: {
    width: 52,
    height: 52,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#1A1A1A',
  },
  thumb: { width: 52, height: 52 },
  thumbOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbFailed: { backgroundColor: 'rgba(255,68,68,0.4)' },
  thumbOverlayText: { color: '#FF4444', fontFamily: 'Inter', fontSize: 14 },
  removeBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#555555',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageBtn: {
    width: 44,
    height: 44,
    backgroundColor: '#1A1A1A',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageBtnDisabled: { opacity: 0.5 },
  waitText: { fontFamily: 'Inter', fontSize: 11, color: '#888888', letterSpacing: 1 },
});
