import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: brandColors.cream },
  nav: {
    height: 104,
    backgroundColor: brandColors.cream,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 62,
  },
  navCircleButton: {
    position: 'absolute',
    top: 21,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: brandColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: brandColors.ink,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  navBackButton: { left: 22 },
  navMoreButton: { right: 22 },
  navTitle: {
    fontFamily: brandTypography.display,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: brandColors.ink,
    textAlign: 'center',
  },
  navCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    gap: 4,
    minWidth: 0,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: brandRgba.white88,
  },
  statusDot: { width: 5, height: 5, borderRadius: 2.5 },
  statusBadgeText: {
    fontFamily: 'Inter',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '500',
    letterSpacing: 0,
    color: brandColors.ink,
  },
  endpointRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    maxWidth: '100%',
  },
  endpointName: {
    flexShrink: 1,
    fontFamily: 'Inter',
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '500',
    color: brandColors.textSoft,
  },
  connectionDot: { width: 4, height: 4, borderRadius: 2 },
  connectionText: {
    flexShrink: 0,
    fontFamily: 'Inter',
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '600',
    color: brandColors.cyan,
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 20 },
  olderMessagesLoading: {
    height: 40,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  workedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    paddingVertical: 2,
    paddingHorizontal: 0,
  },
  workedText: {
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.textSoft,
  },
  workedExpandedItems: {
    gap: 20,
    marginTop: 16,
  },
  inputArea: {
    backgroundColor: brandColors.cream,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 22,
  },
  safeArea: { height: 0, backgroundColor: brandColors.cream },
});
