import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#040D04' },
  nav: {
    height: 52,
    backgroundColor: '#061206',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#0F2B0F',
  },
  navTitle: { fontFamily: 'Anton', fontSize: 16, color: '#20C20E' },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(32,194,14,0.25)',
  },
  statusDot: { width: 6, height: 6, borderRadius: 2 },
  statusBadgeText: {
    fontFamily: 'Inter',
    fontSize: 9,
    fontWeight: '700' as const,
    letterSpacing: 1.5,
    color: '#33FF33',
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 12 },
  inputBar: {
    minHeight: 60,
    maxHeight: 160,
    backgroundColor: '#061206',
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#0F2B0F',
  },
  inputField: {
    flex: 1,
    minHeight: 36,
    maxHeight: 120,
    backgroundColor: '#0A1A0A',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#0F2B0F',
    paddingHorizontal: 14,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  inputDisabled: { opacity: 0.4 },
  input: { fontFamily: 'Geist', fontSize: 14, color: '#20C20E', minHeight: 20 },
  waitText: { fontFamily: 'Geist Mono', fontSize: 10, color: '#33FF33', letterSpacing: 1 },
  previewRow: {
    backgroundColor: '#040D04',
    maxHeight: 68,
  },
  previewRowContent: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  thumbWrapper: {
    width: 52,
    height: 52,
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: '#0A1A0A',
  },
  thumb: {
    width: 52,
    height: 52,
  },
  thumbOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(4,13,4,0.67)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbFailed: { backgroundColor: 'rgba(26,0,0,0.67)' },
  thumbOverlayText: { color: '#FF4444', fontFamily: 'Geist Mono', fontSize: 14 },
  removeBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 18,
    height: 18,
    borderRadius: 2,
    backgroundColor: '#0A1A0A',
    borderWidth: 1,
    borderColor: '#2D8B2D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageBtn: {
    width: 36,
    height: 36,
    backgroundColor: '#0A1A0A',
    borderWidth: 1,
    borderColor: '#0F2B0F',
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageBtnDisabled: { opacity: 0.5 },
});
