import { StyleSheet } from 'react-native';

export const addEndpointModalStyles = StyleSheet.create({
  fullScreen: { flex: 1, backgroundColor: '#0D0D0D' },
  fullNav: {
    height: 52,
    backgroundColor: '#0D0D0D',
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E1E',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 104,
    height: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderRadius: 18,
  },
  backText: { fontFamily: 'Inter', fontSize: 15, fontWeight: '600', color: '#FF6B35' },
  fullNavTitle: { fontFamily: 'Inter', fontSize: 15, fontWeight: '700', color: '#FFFFFF' },
  navSpacer: { width: 104 },
  fullScroll: { flex: 1 },
  fullContent: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 34, gap: 14 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  fullTitle: { fontFamily: 'Inter', fontSize: 28, fontWeight: '700', color: '#FFFFFF' },
  contentCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullSubtitle: {
    marginTop: -8,
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
    color: '#888888',
  },
  scanHeader: { flexDirection: 'row' },
  scanBadge: {
    height: 44,
    minWidth: 142,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    backgroundColor: '#FF6B35',
    borderRadius: 12,
  },
  scanBadgeText: { fontFamily: 'Inter', fontSize: 12, fontWeight: '700', color: '#FFFFFF' },
  fullHelpButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  qrCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 18,
    gap: 8,
  },
  qrCardTitle: { fontFamily: 'Inter', fontSize: 17, fontWeight: '700', color: '#FFFFFF' },
  qrCardSubtitle: { fontFamily: 'Inter', fontSize: 12, lineHeight: 16, color: '#888888' },
  fullScannerBox: { marginTop: 8 },
  commandHint: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    backgroundColor: '#1A1A1A',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  commandHintText: { flex: 1, fontFamily: 'Inter', fontSize: 13, lineHeight: 17, color: '#DDDDDD' },
  errText: { fontFamily: 'Inter', fontSize: 12, color: '#FF4444' },
  camera: { width: '100%', height: 220, borderRadius: 10 },
  permBtn: {
    height: 220,
    backgroundColor: '#252525',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permText: { fontFamily: 'Inter', fontSize: 13, color: '#888888' },
  helpOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-end' },
  helpScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.58)' },
  helpSheet: {
    minHeight: 470,
    maxHeight: '76%',
    backgroundColor: '#161616',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderTopColor: '#2A2A2A',
    paddingTop: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 62,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#2A2A2A',
    marginBottom: 14,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  sheetTitleBlock: { flex: 1, gap: 4 },
  sheetTitle: { fontFamily: 'Inter', fontSize: 20, fontWeight: '700', color: '#FFFFFF' },
  sheetSubtitle: { fontFamily: 'Inter', fontSize: 12, lineHeight: 16, color: '#888888' },
  sheetCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commandsScroll: { flex: 1 },
  commandsContent: { paddingHorizontal: 20, paddingBottom: 28, gap: 10 },
  registerTitle: {
    marginTop: 2,
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  commandBlock: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    padding: 12,
    gap: 8,
  },
  commandBlockCompact: { gap: 6 },
  commandHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  commandTitle: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
  commandTitleAccent: { fontSize: 11, color: '#FF6B35' },
  copyButton: {
    minWidth: 34,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  copiedText: { fontFamily: 'Inter', fontSize: 9, fontWeight: '700', color: '#4CAF50' },
  commandText: { fontFamily: 'Inter', fontSize: 10, lineHeight: 14, color: '#DDDDDD' },
});
