import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const addEndpointModalStyles = StyleSheet.create({
  fullScreen: { flex: 1, backgroundColor: brandColors.cream },
  fullNav: {
    height: 48,
    backgroundColor: brandColors.cream,
    borderBottomWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 90,
    height: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    borderRadius: 16,
  },
  backText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: brandColors.ink },
  fullNavTitle: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: brandColors.ink },
  navSpacer: { width: 90 },
  fullScroll: { flex: 1 },
  fullContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 28, gap: 12 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  fullTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '700',
    color: brandColors.ink,
  },
  contentCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullSubtitle: {
    marginTop: -4,
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 16,
    color: brandColors.textSoft,
  },
  scanHeader: { flexDirection: 'row' },
  modeTabs: { flexDirection: 'row', gap: 8 },
  modeTab: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 14,
    borderRadius: 19,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
  },
  modeTabActive: {
    backgroundColor: brandColors.ink,
    borderColor: brandColors.ink,
  },
  modeTabText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '700',
    color: brandColors.textSoft,
  },
  modeTabTextActive: { color: brandColors.white },
  fullHelpButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  qrCard: {
    backgroundColor: brandRgba.white88,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: brandColors.silver,
    padding: 14,
    gap: 8,
  },
  qrCardTitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
    color: brandColors.ink,
  },
  qrCardSubtitle: {
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 15,
    color: brandColors.textSoft,
  },
  fullScannerBox: { marginTop: 6 },
  inlineCommandsSection: {
    backgroundColor: brandRgba.white88,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: brandColors.silver,
    padding: 12,
    gap: 8,
  },
  inlineCommandsSectionTitle: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '700',
    color: brandColors.textSoft,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  inlineRegisterTitle: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '700',
    color: brandColors.coral,
    marginTop: 2,
  },
  errText: { fontFamily: 'Inter', fontSize: 12, color: brandColors.error },
  camera: { width: '100%', height: 210, borderRadius: 10 },
  permBtn: {
    height: 210,
    backgroundColor: brandRgba.ink18,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permText: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft },
  helpOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-end' },
  helpScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.58)' },
  helpSheet: {
    minHeight: 430,
    maxHeight: '72%',
    backgroundColor: brandColors.cream,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderTopColor: brandColors.silver,
    paddingTop: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 62,
    height: 5,
    borderRadius: 999,
    backgroundColor: brandColors.silver,
    marginBottom: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  sheetTitleBlock: { flex: 1, gap: 4 },
  sheetTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: brandColors.ink,
  },
  sheetSubtitle: { fontFamily: 'Inter', fontSize: 11, lineHeight: 15, color: brandColors.textSoft },
  sheetCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commandsScroll: { flex: 1 },
  commandsContent: { paddingHorizontal: 16, paddingBottom: 24, gap: 8 },
  registerTitle: {
    marginTop: 2,
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.ink,
  },
  commandBlock: {
    backgroundColor: brandRgba.white88,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: brandColors.silver,
    padding: 10,
    gap: 6,
  },
  commandBlockCompact: { gap: 6 },
  commandHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  commandTitle: { fontFamily: 'Inter', fontSize: 12, fontWeight: '700', color: brandColors.ink },
  commandTitleAccent: { fontSize: 10, color: brandColors.coral },
  copyButton: {
    minWidth: 34,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  copiedText: { fontFamily: 'Inter', fontSize: 9, fontWeight: '700', color: brandColors.lime },
  commandText: { fontFamily: 'Inter', fontSize: 10, lineHeight: 14, color: brandColors.ink },
  manualCard: {
    backgroundColor: brandRgba.white88,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: brandColors.silver,
    padding: 14,
    gap: 4,
  },
  manualCardSubtitle: {
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 15,
    color: brandColors.textSoft,
    marginBottom: 4,
  },
  fieldLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: brandColors.textSoft,
    marginTop: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  textInput: {
    backgroundColor: brandColors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: brandColors.silver,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.ink,
  },
  pasteLink: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingVertical: 4,
  },
  pasteLinkText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.coral,
  },
  connectButton: {
    marginTop: 12,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: brandColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectButtonDisabled: {
    opacity: 0.55,
  },
  connectButtonText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.white,
  },
  manualErrText: {
    marginTop: 6,
    fontFamily: 'Inter',
    fontSize: 12,
    color: brandColors.error,
  },
});
