import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const addEndpointModalStyles = StyleSheet.create({
  fullScreen: { flex: 1, backgroundColor: brandColors.cream },
  fullNav: {
    height: 52,
    backgroundColor: brandColors.cream,
    borderBottomWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 104,
    height: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    borderRadius: 18,
  },
  backText: { fontFamily: 'Inter', fontSize: 15, fontWeight: '700', color: brandColors.ink },
  fullNavTitle: { fontFamily: 'Inter', fontSize: 15, fontWeight: '700', color: brandColors.ink },
  navSpacer: { width: 104 },
  fullScroll: { flex: 1 },
  fullContent: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 34, gap: 14 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  fullTitle: {
    fontFamily: brandTypography.display,
    fontSize: 34,
    fontWeight: '900',
    color: brandColors.ink,
  },
  contentCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullSubtitle: {
    marginTop: -8,
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
    color: brandColors.textSoft,
  },
  scanHeader: { flexDirection: 'row' },
  scanBadge: {
    height: 44,
    minWidth: 142,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    backgroundColor: brandColors.ink,
    borderRadius: 22,
  },
  scanBadgeText: { fontFamily: 'Inter', fontSize: 12, fontWeight: '700', color: brandColors.white },
  fullHelpButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  qrCard: {
    backgroundColor: brandRgba.white88,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brandColors.silver,
    padding: 18,
    gap: 8,
  },
  qrCardTitle: { fontFamily: 'Inter', fontSize: 17, fontWeight: '800', color: brandColors.ink },
  qrCardSubtitle: {
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 16,
    color: brandColors.textSoft,
  },
  fullScannerBox: { marginTop: 8 },
  commandHint: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    backgroundColor: brandRgba.white88,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: brandColors.silver,
  },
  commandHintText: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 17,
    color: brandColors.ink,
  },
  errText: { fontFamily: 'Inter', fontSize: 12, color: brandColors.error },
  camera: { width: '100%', height: 220, borderRadius: 10 },
  permBtn: {
    height: 220,
    backgroundColor: brandRgba.ink18,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permText: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft },
  helpOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-end' },
  helpScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.58)' },
  helpSheet: {
    minHeight: 470,
    maxHeight: '76%',
    backgroundColor: brandColors.cream,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderTopColor: brandColors.silver,
    paddingTop: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 62,
    height: 5,
    borderRadius: 999,
    backgroundColor: brandColors.silver,
    marginBottom: 14,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  sheetTitleBlock: { flex: 1, gap: 4 },
  sheetTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    fontWeight: '900',
    color: brandColors.ink,
  },
  sheetSubtitle: { fontFamily: 'Inter', fontSize: 12, lineHeight: 16, color: brandColors.textSoft },
  sheetCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commandsScroll: { flex: 1 },
  commandsContent: { paddingHorizontal: 20, paddingBottom: 28, gap: 10 },
  registerTitle: {
    marginTop: 2,
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.ink,
  },
  commandBlock: {
    backgroundColor: brandRgba.white88,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: brandColors.silver,
    padding: 12,
    gap: 8,
  },
  commandBlockCompact: { gap: 6 },
  commandHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  commandTitle: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: brandColors.ink },
  commandTitleAccent: { fontSize: 11, color: brandColors.coral },
  copyButton: {
    minWidth: 34,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  copiedText: { fontFamily: 'Inter', fontSize: 9, fontWeight: '700', color: brandColors.lime },
  commandText: { fontFamily: 'Inter', fontSize: 10, lineHeight: 14, color: brandColors.ink },
});
