import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandShadow, brandTypography } from '@/theme/brandRefresh';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: brandColors.cream },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 16, paddingBottom: 126 },
  nav: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '700',
    color: brandColors.ink,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...brandShadow,
  },
  hero: {
    minHeight: 138,
    borderRadius: 20,
    backgroundColor: brandRgba.cyanWash,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    overflow: 'hidden',
    ...brandShadow,
  },
  heroMascot: { width: 108, height: 108, marginLeft: -6, marginRight: 8 },
  heroContent: { flex: 1, minWidth: 0 },
  heroTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: brandColors.ink,
  },
  heroMeta: {
    marginTop: 6,
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.textSoft,
  },
  scanButton: {
    marginTop: 10,
    height: 40,
    borderRadius: 20,
    backgroundColor: brandColors.ink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  scanText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: brandColors.white },
  sectionHeader: {
    marginTop: 20,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionLabel: {
    fontFamily: brandTypography.display,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '700',
    color: brandColors.ink,
  },
  manageWrap: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  manageText: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft },
  sectionCard: {
    borderRadius: 18,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    overflow: 'hidden',
    ...brandShadow,
  },
  row: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  divider: { borderBottomWidth: 1, borderBottomColor: brandRgba.silver78 },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowCopy: { flex: 1, minWidth: 0 },
  rowTitle: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
    color: brandColors.ink,
  },
  rowSubtitle: {
    marginTop: 3,
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 15,
    color: brandColors.textMuted,
  },
  destructiveSubtitle: { color: brandColors.coral },
  disabledRow: { opacity: 0.64 },
});
