import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandShadow, brandTypography } from '@/theme/brandRefresh';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: brandColors.cream },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 16, paddingBottom: 126 },
  nav: {
    minHeight: 108,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navTitle: {
    fontFamily: brandTypography.display,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    color: brandColors.ink,
  },
  addButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...brandShadow,
  },
  hero: {
    minHeight: 166,
    borderRadius: 28,
    backgroundColor: brandRgba.cyanWash,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    overflow: 'hidden',
    ...brandShadow,
  },
  heroMascot: { width: 136, height: 136, marginLeft: -8, marginRight: 10 },
  heroContent: { flex: 1, minWidth: 0 },
  heroTitle: {
    fontFamily: brandTypography.display,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '700',
    color: brandColors.ink,
  },
  heroMeta: {
    marginTop: 6,
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 20,
    color: brandColors.textSoft,
  },
  scanButton: {
    marginTop: 14,
    height: 48,
    borderRadius: 24,
    backgroundColor: brandColors.ink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 16,
  },
  scanText: { fontFamily: 'Inter', fontSize: 16, fontWeight: '800', color: brandColors.white },
  sectionHeader: {
    marginTop: 24,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionLabel: {
    fontFamily: brandTypography.display,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '700',
    color: brandColors.ink,
  },
  manageWrap: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  manageText: { fontFamily: 'Inter', fontSize: 15, color: brandColors.textSoft },
  sectionCard: {
    borderRadius: 22,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    overflow: 'hidden',
    ...brandShadow,
  },
  row: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  divider: { borderBottomWidth: 1, borderBottomColor: brandRgba.silver78 },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowCopy: { flex: 1, minWidth: 0 },
  rowTitle: { fontFamily: 'Inter', fontSize: 15, fontWeight: '700', color: brandColors.ink },
  rowSubtitle: {
    marginTop: 3,
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
    color: brandColors.textMuted,
  },
  destructiveSubtitle: { color: brandColors.coral },
  disabledRow: { opacity: 0.64 },
});
