import { StyleSheet } from 'react-native';

export const activityScreenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0D0D0D' },
  header: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 14, gap: 14 },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontFamily: 'Inter', fontSize: 34, fontWeight: '700', color: '#FFFFFF' },
  segment: {
    flexDirection: 'row',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 3,
    gap: 3,
  },
  segmentItem: {
    flex: 1,
    minHeight: 36,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  segmentItemActive: { backgroundColor: '#2A2A2A' },
  segmentText: { fontFamily: 'Inter', fontSize: 12, fontWeight: '700', color: '#888888' },
  segmentTextActive: { color: '#FFFFFF' },
  tabUnreadDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#FF6B35' },
  content: { paddingHorizontal: 16, paddingBottom: 110, gap: 14 },
  doneHeader: { gap: 12 },
  doneSegment: { flexDirection: 'row', backgroundColor: '#111111', borderRadius: 8, padding: 3 },
  doneSegmentItem: {
    flex: 1,
    minHeight: 34,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneSegmentItemActive: { backgroundColor: '#FF6B35' },
  doneSegmentText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: '#888888' },
  doneSegmentTextActive: { color: '#FFFFFF' },
  markReadText: {
    alignSelf: 'flex-end',
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: '#FF6B35',
  },
  list: { borderTopWidth: 1, borderTopColor: '#1A1A1A' },
  loadMoreFooter: {
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadMoreText: { fontFamily: 'Inter', fontSize: 13, color: '#888888' },
  loadMoreRetryText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: '#FF6B35' },
  row: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1A1A1A',
  },
  rowDot: { width: 8, height: 8, borderRadius: 4 },
  dotAttention: { backgroundColor: '#FF6B35' },
  dotRunning: { backgroundColor: '#4CAF50' },
  dotFailed: { backgroundColor: '#FF4444' },
  dotRead: { backgroundColor: '#0D0D0D' },
  rowBody: { flex: 1, gap: 5 },
  rowTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  itemTitle: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    color: '#DDDDDD',
    lineHeight: 22,
  },
  itemTitleUnread: { color: '#FFFFFF', fontWeight: '700' },
  timeText: { fontFamily: 'Inter', fontSize: 12, color: '#555555', paddingTop: 2 },
  subtitle: { fontFamily: 'Inter', fontSize: 13, color: '#666666', lineHeight: 18 },
  rowRight: { alignItems: 'flex-end', justifyContent: 'center', gap: 6 },
  statusLabel: { fontFamily: 'Inter', fontSize: 11, fontWeight: '700', color: '#888888' },
  statusRunning: { color: '#4CAF50' },
  statusFailed: { color: '#FF4444' },
  emptySectionText: { fontFamily: 'Inter', fontSize: 14, color: '#666666', paddingVertical: 18 },
  deleteAction: {
    width: 80,
    backgroundColor: '#1A1A1A',
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#FF4444',
  },
  deleteText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '600', color: '#FF4444' },
  partialFailure: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
  },
  partialFailureText: { flex: 1, fontFamily: 'Inter', fontSize: 12, color: '#DDDDDD' },
  partialFailureRetry: { fontFamily: 'Inter', fontSize: 12, fontWeight: '700', color: '#FF6B35' },
  emptyBody: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingBottom: 80,
  },
  emptyIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#1A1A1A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  emptyTitle: { fontFamily: 'Inter', fontSize: 22, fontWeight: '700', color: '#FFFFFF' },
  emptyDesc: {
    marginTop: 8,
    fontFamily: 'Inter',
    fontSize: 14,
    color: '#888888',
    textAlign: 'center',
    lineHeight: 20,
  },
  retryButton: {
    marginTop: 18,
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: '#FF6B35',
    paddingHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  retryText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
});
