import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const activityScreenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.cream },
  header: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 14, gap: 14 },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: {
    fontFamily: brandTypography.display,
    fontSize: 56,
    fontWeight: '900',
    color: brandColors.ink,
  },
  segment: {
    flexDirection: 'row',
    backgroundColor: brandRgba.white88,
    borderRadius: 26,
    padding: 5,
    gap: 3,
    borderWidth: 1,
    borderColor: brandColors.silver,
  },
  segmentItem: {
    flex: 1,
    minHeight: 36,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  segmentItemActive: { backgroundColor: brandRgba.cyanWash },
  segmentText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.textSoft,
  },
  segmentTextActive: { color: brandColors.ink },
  tabUnreadDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: brandColors.coral },
  content: { paddingHorizontal: 16, paddingBottom: 126, gap: 14 },
  doneHeader: { gap: 12 },
  doneSegment: {
    flexDirection: 'row',
    backgroundColor: brandRgba.white70,
    borderRadius: 18,
    padding: 3,
  },
  doneSegmentItem: {
    flex: 1,
    minHeight: 34,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneSegmentItemActive: { backgroundColor: brandColors.ink },
  doneSegmentText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.textSoft,
  },
  doneSegmentTextActive: { color: brandColors.white },
  markReadText: {
    alignSelf: 'flex-end',
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.coral,
  },
  list: { borderTopWidth: 0 },
  loadMoreFooter: {
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadMoreText: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textMuted },
  loadMoreRetryText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.coral,
  },
  row: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderRadius: 20,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    paddingHorizontal: 14,
  },
  rowDot: { width: 8, height: 8, borderRadius: 4 },
  dotAttention: { backgroundColor: brandColors.coral },
  dotRunning: { backgroundColor: brandColors.cyan },
  dotFailed: { backgroundColor: brandColors.error },
  dotRead: { backgroundColor: brandColors.lime },
  rowBody: { flex: 1, gap: 5 },
  rowTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  itemTitle: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    color: brandColors.ink,
    lineHeight: 22,
  },
  itemTitleUnread: { color: brandColors.ink, fontWeight: '800' },
  timeText: { fontFamily: 'Inter', fontSize: 12, color: brandColors.textMuted, paddingTop: 2 },
  subtitle: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft, lineHeight: 18 },
  rowRight: { alignItems: 'flex-end', justifyContent: 'center', gap: 6 },
  statusLabel: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '700',
    color: brandColors.textMuted,
  },
  statusRunning: { color: brandColors.cyan },
  statusFailed: { color: brandColors.error },
  emptySectionText: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: brandColors.textSoft,
    paddingVertical: 18,
  },
  deleteAction: {
    width: 80,
    backgroundColor: brandColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: brandColors.error,
  },
  deleteText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '600', color: brandColors.error },
  partialFailure: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    backgroundColor: brandRgba.white88,
    borderRadius: 8,
    padding: 12,
  },
  partialFailureText: { flex: 1, fontFamily: 'Inter', fontSize: 12, color: brandColors.ink },
  partialFailureRetry: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.coral,
  },
  emptyBody: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingBottom: 80,
  },
  emptyIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: brandRgba.white88,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  emptyTitle: {
    fontFamily: brandTypography.display,
    fontSize: 24,
    fontWeight: '900',
    color: brandColors.ink,
  },
  emptyDesc: {
    marginTop: 8,
    fontFamily: 'Inter',
    fontSize: 14,
    color: brandColors.textSoft,
    textAlign: 'center',
    lineHeight: 20,
  },
  retryButton: {
    marginTop: 18,
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: brandColors.ink,
    paddingHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  retryText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '700', color: brandColors.white },
});
