import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const workflowScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: brandColors.cream,
  },
  header: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  headerTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '700',
    color: brandColors.ink,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  emptyText: {
    fontFamily: brandTypography.display,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '700',
    color: brandColors.ink,
    textAlign: 'center',
    marginBottom: 6,
  },
  emptySubtext: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 18,
    color: brandColors.textMuted,
    textAlign: 'center',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 126,
  },
  row: {
    backgroundColor: brandRgba.white88,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brandColors.silver,
    minHeight: 62,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowInfo: {
    flex: 1,
    minWidth: 0,
    marginRight: 10,
  },
  rowName: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
    color: brandColors.ink,
    marginBottom: 2,
  },
  rowMeta: {
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 15,
    color: brandColors.textSoft,
  },
  // Form styles
  formRoot: {
    flex: 1,
    backgroundColor: brandColors.cream,
  },
  formHeader: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  formTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: brandColors.ink,
  },
  formCancel: {
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.textSoft,
  },
  formSave: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '600',
    color: brandColors.coral,
  },
  formSaveDisabled: {
    color: brandColors.textMuted,
  },
  formContent: {
    paddingHorizontal: 16,
    paddingBottom: 126,
  },
  fieldLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: brandColors.textSoft,
    marginBottom: 5,
    marginTop: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  textInput: {
    backgroundColor: brandRgba.white88,
    borderRadius: 10,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.ink,
  },
  textInputMultiline: {
    minHeight: 76,
    textAlignVertical: 'top',
  },
  segment: {
    flexDirection: 'row',
    backgroundColor: brandRgba.white88,
    borderRadius: 10,
    padding: 3,
  },
  segmentItem: {
    flex: 1,
    paddingVertical: 7,
    alignItems: 'center',
    borderRadius: 8,
  },
  segmentItemActive: {
    backgroundColor: brandColors.ink,
  },
  segmentText: {
    fontFamily: 'Inter',
    fontSize: 12,
    color: brandColors.textSoft,
  },
  segmentTextActive: {
    color: brandColors.white,
    fontWeight: '600',
  },
  agentRow: {
    backgroundColor: brandRgba.white88,
    borderRadius: 10,
    minHeight: 56,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  agentRowSelected: {
    borderWidth: 1,
    borderColor: brandColors.coral,
  },
  agentCopy: { flex: 1, minWidth: 0 },
  agentName: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 17,
    color: brandColors.ink,
  },
  agentEndpoint: {
    fontFamily: 'Inter',
    fontSize: 11,
    color: brandColors.textSoft,
  },
  // Template picker styles
  pickerRoot: {
    flex: 1,
    backgroundColor: brandColors.cream,
  },
  pickerHeader: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  pickerCancel: {
    width: 58,
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.textSoft,
  },
  pickerTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: brandColors.ink,
  },
  pickerHeaderSpacer: {
    width: 58,
  },
  pickerContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  templateCard: {
    backgroundColor: brandRgba.white88,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: brandColors.silver,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  blankTemplateCard: {
    borderColor: brandColors.ink,
  },
  blankEyebrow: {
    fontFamily: 'Inter',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
    color: brandColors.coral,
    letterSpacing: 1,
    marginBottom: 5,
  },
  blankTitle: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
    color: brandColors.ink,
    marginBottom: 3,
  },
  blankSchedule: {
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 15,
    color: brandColors.textSoft,
    marginTop: 6,
  },
  templateSectionLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
    color: brandColors.textSoft,
    letterSpacing: 1,
    marginTop: 6,
    marginBottom: 8,
  },
  templateHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 5,
  },
  templateTitle: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
    color: brandColors.ink,
  },
  templateScheduleChip: {
    flexShrink: 0,
    maxWidth: 132,
    borderRadius: 8,
    backgroundColor: brandRgba.cyanSoft,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  templateScheduleText: {
    fontFamily: 'Inter',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
    color: brandColors.ink,
  },
  templateDescription: {
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 16,
    color: brandColors.textSoft,
  },
  templateBoundaryBlock: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: brandRgba.silver78,
    gap: 3,
  },
  templateBoundaryLabel: {
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    color: brandColors.coral,
  },
  templateBoundaryDescription: {
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 15,
    color: brandColors.textMuted,
  },
});
