import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const specDetailScreenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.cream },
  header: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  backButton: { minWidth: 72, minHeight: 44, flexDirection: 'row', alignItems: 'center' },
  backText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.ink,
  },
  headerTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    fontWeight: '700',
    color: brandColors.ink,
  },
  headerSpacer: { width: 72 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyTitle: {
    fontFamily: brandTypography.display,
    fontSize: 20,
    fontWeight: '700',
    color: brandColors.ink,
  },
  content: { padding: 16, gap: 12 },
  hero: {
    minHeight: 72,
    borderRadius: 16,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
  },
  heroIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: brandRgba.cyanSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBody: { flex: 1, minWidth: 0 },
  title: {
    fontFamily: brandTypography.display,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: '700',
    color: brandColors.ink,
  },
  subtitle: {
    marginTop: 3,
    fontFamily: brandTypography.body,
    fontSize: 11,
    color: brandColors.textSoft,
  },
  statusPill: {
    minHeight: 26,
    borderRadius: 13,
    paddingHorizontal: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: brandRgba.limeSoft,
  },
  statusText: {
    fontFamily: brandTypography.body,
    fontSize: 10,
    fontWeight: '800',
    color: brandColors.ink,
  },
  metricGrid: { flexDirection: 'row', gap: 10 },
  metric: {
    flex: 1,
    minHeight: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: brandColors.silver,
    backgroundColor: brandRgba.white88,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
  },
  metricLabel: { fontFamily: brandTypography.body, fontSize: 10, color: brandColors.textSoft },
  metricValue: {
    marginTop: 2,
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.ink,
  },
  section: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: brandColors.silver,
    backgroundColor: brandRgba.white88,
    padding: 14,
    gap: 10,
  },
  sectionTitle: {
    fontFamily: brandTypography.body,
    fontSize: 11,
    fontWeight: '800',
    color: brandColors.coral,
  },
  bodyText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    lineHeight: 19,
    color: brandColors.ink,
  },
  infoRow: {
    minHeight: 34,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  infoLabel: { fontFamily: brandTypography.body, fontSize: 12, color: brandColors.textSoft },
  infoValue: {
    flex: 1,
    textAlign: 'right',
    fontFamily: brandTypography.body,
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.ink,
  },
  inlineButton: {
    minHeight: 40,
    borderRadius: 10,
    backgroundColor: brandRgba.ink08,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  inlineButtonText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.ink,
  },
  actionRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 10 },
  actionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: brandRgba.ink08,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBody: { flex: 1, minWidth: 0 },
  actionLabel: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.ink,
  },
  actionValue: {
    marginTop: 2,
    fontFamily: brandTypography.body,
    fontSize: 11,
    color: brandColors.textSoft,
  },
  errorText: {
    fontFamily: brandTypography.body,
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.error,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: brandRgba.white88,
    borderTopWidth: 1,
    borderTopColor: brandColors.silver,
  },
  primaryButton: {
    minHeight: 46,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: brandColors.ink,
  },
  primaryText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.white,
  },
  disabled: { opacity: 0.45 },
});
