import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const specsHomeStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.cream },
  header: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  title: {
    fontFamily: brandTypography.display,
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '700',
    color: brandColors.ink,
  },
  subtitle: { marginTop: 2, fontFamily: 'Inter', fontSize: 12, color: brandColors.textSoft },
  headerActions: { flexDirection: 'row', gap: 8 },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
  },
  disabled: { opacity: 0.45 },
  segment: {
    height: 34,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: brandRgba.white88,
    flexDirection: 'row',
    padding: 3,
    borderWidth: 1,
    borderColor: brandColors.silver,
  },
  segmentItem: { flex: 1, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  segmentItemActive: { backgroundColor: brandRgba.cyanWash },
  segmentText: { fontFamily: 'Inter', fontSize: 12, color: brandColors.textSoft },
  segmentTextActive: { color: brandColors.ink, fontWeight: '700' },
  attention: {
    minHeight: 44,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: brandColors.coral,
    backgroundColor: brandRgba.white88,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  attentionText: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '700',
    color: brandColors.ink,
  },
  attentionAction: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '800',
    color: brandColors.coral,
  },
  content: { paddingHorizontal: 16, paddingBottom: 126, gap: 14 },
  section: { gap: 8 },
  sectionHeaderButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  sectionTitle: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '800',
    color: brandColors.textSoft,
    textTransform: 'uppercase',
  },
  sectionCount: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.textMuted,
  },
  capture: {
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  captureText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
    color: brandColors.textSoft,
  },
  captureActions: { flexDirection: 'row', gap: 8 },
  miniAction: {
    minHeight: 44,
    flex: 1,
    borderRadius: 12,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  miniActionText: { fontFamily: 'Inter', fontSize: 11, fontWeight: '700', color: brandColors.ink },
  group: {
    borderRadius: 14,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    overflow: 'hidden',
  },
  row: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  ideaIcon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: brandRgba.cyanSoft,
  },
  docIcon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: brandRgba.limeSoft,
  },
  statusDot: { width: 9, height: 9, borderRadius: 5 },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
    color: brandColors.ink,
  },
  rowSubtitle: { marginTop: 2, fontFamily: 'Inter', fontSize: 12, color: brandColors.textSoft },
  rowMetaText: { marginTop: 2, fontFamily: 'Inter', fontSize: 11, color: brandColors.textMuted },
  trailing: { minWidth: 76, alignItems: 'flex-end', gap: 5 },
  statusText: { fontFamily: 'Inter', fontSize: 11, fontWeight: '800', color: brandColors.ink },
  divider: { height: 1, marginLeft: 54, backgroundColor: brandRgba.silver78 },
  rowAction: {
    width: 92,
    backgroundColor: brandRgba.white88,
    borderLeftWidth: 1,
    borderLeftColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  rowActionText: { fontFamily: 'Inter', fontSize: 11, fontWeight: '800', color: brandColors.ink },
  rowDeleteAction: {
    width: 74,
    backgroundColor: brandColors.white,
    borderLeftWidth: 1,
    borderLeftColor: brandColors.error,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 4,
  },
  rowDeleteText: { fontFamily: 'Inter', fontSize: 11, fontWeight: '700' as const, color: brandColors.error },
  empty: {
    minHeight: 88,
    borderRadius: 14,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    gap: 6,
  },
  emptyTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: brandColors.ink,
    textAlign: 'center',
  },
  emptyBody: {
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.textSoft,
    textAlign: 'center',
  },
  emptyAction: {
    minHeight: 44,
    borderRadius: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: brandColors.ink,
  },
  emptyActionText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.white,
  },
  undo: {
    position: 'absolute',
    left: 16,
    right: 16,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: brandColors.ink,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  undoText: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.white,
  },
  undoButton: { minHeight: 44, justifyContent: 'center' },
  undoButtonText: { fontFamily: 'Inter', fontSize: 13, fontWeight: '900', color: brandColors.lime },
});
