import { StyleSheet } from 'react-native';
import { brandColors, brandRgba, brandTypography } from '@/theme/brandRefresh';

export const projectDetailStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.cream },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  errorTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    fontWeight: '700',
    color: brandColors.error,
  },
  errorBtn: {
    borderWidth: 1,
    borderColor: brandColors.coral,
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 10,
  },
  errorBtnText: {
    fontFamily: brandTypography.body,
    fontSize: 14,
    fontWeight: '600',
    color: brandColors.coral,
  },
  navRow: { height: 54, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' },
  circleBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: brandRgba.silver78,
    backgroundColor: brandRgba.white70,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: brandColors.ink,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  scroll: { paddingHorizontal: 16 },
  heroCard: {
    borderRadius: 28,
    padding: 18,
    marginBottom: 12,
    backgroundColor: brandColors.ink,
    shadowColor: brandColors.ink,
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  heroEyebrow: {
    fontFamily: brandTypography.body,
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.silver,
    marginBottom: 3,
  },
  heroTitle: {
    fontFamily: brandTypography.display,
    fontSize: 32,
    fontWeight: '800',
    color: brandColors.white,
    lineHeight: 36,
  },
  heroMeta: {
    fontFamily: brandTypography.body,
    fontSize: 12.5,
    color: brandColors.silver,
    marginTop: 4,
  },
  statsRow: {
    flexDirection: 'row',
    marginTop: 16,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: brandColors.darkPanel,
  },
  statItem: { flex: 1, height: 62, alignItems: 'center', justifyContent: 'center' },
  statNum: {
    fontFamily: brandTypography.display,
    fontSize: 24,
    fontWeight: '800',
    color: brandColors.white,
  },
  statLabel: {
    fontFamily: brandTypography.body,
    fontSize: 11,
    fontWeight: '700',
    color: brandColors.silver,
    marginTop: 4,
  },
  statDivider: { width: 1, backgroundColor: brandColors.darkLine, marginVertical: 10 },
  resourceHeroCard: {
    borderRadius: 28,
    padding: 18,
    marginBottom: 12,
    backgroundColor: brandRgba.limeSoft,
    borderWidth: 1,
    borderColor: brandColors.silver,
    shadowColor: brandColors.ink,
    shadowOpacity: 0.07,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  resourceEyebrow: {
    fontFamily: brandTypography.body,
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.textSoft,
    marginBottom: 3,
  },
  resourceHeroTitle: {
    fontFamily: brandTypography.display,
    fontSize: 32,
    fontWeight: '800',
    color: brandColors.ink,
    lineHeight: 36,
  },
  resourceHeroDesc: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    color: brandColors.textSoft,
    marginTop: 7,
    lineHeight: 18,
  },
  segmented: {
    height: 40,
    padding: 4,
    borderRadius: 20,
    marginBottom: 14,
    backgroundColor: brandRgba.ink08,
    flexDirection: 'row',
  },
  segment: { flex: 1, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  segmentActive: {
    backgroundColor: brandColors.white,
    shadowColor: brandColors.ink,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  segmentText: {
    fontFamily: brandTypography.body,
    fontSize: 12,
    fontWeight: '800',
    color: brandColors.textSoft,
  },
  segmentTextActive: { color: brandColors.ink },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    fontFamily: brandTypography.body,
    fontSize: 18,
    fontWeight: '800',
    color: brandColors.ink,
  },
  sectionMeta: {
    fontFamily: brandTypography.body,
    fontSize: 12,
    fontWeight: '700',
    color: brandColors.textSoft,
  },
  list: { gap: 10, marginBottom: 12 },
  card: {
    borderRadius: 21,
    padding: 12,
    borderWidth: 1,
    borderColor: brandColors.silver,
    backgroundColor: brandRgba.white88,
    shadowColor: brandColors.ink,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  cardTop: { flexDirection: 'row', gap: 11, alignItems: 'flex-start' },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarNumText: {
    fontFamily: brandTypography.display,
    fontSize: 16,
    fontWeight: '900',
    color: brandColors.white,
  },
  avatarAbbrText: {
    fontFamily: brandTypography.display,
    fontSize: 14,
    fontWeight: '800',
    color: brandColors.ink,
  },
  cardBody: { flex: 1, minWidth: 0 },
  cardTitle: {
    fontFamily: brandTypography.body,
    fontSize: 15,
    fontWeight: '800',
    color: brandColors.ink,
  },
  cardMeta: {
    fontFamily: brandTypography.body,
    fontSize: 12.5,
    color: brandColors.textSoft,
    marginTop: 4,
  },
  cardPreview: {
    fontFamily: brandTypography.body,
    fontSize: 12.5,
    color: brandColors.textSoft,
    marginTop: 7,
    lineHeight: 17,
  },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 7 },
  chip: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 11,
    minHeight: 21,
    backgroundColor: brandRgba.ink08,
    justifyContent: 'center',
  },
  chipCyan: { backgroundColor: brandRgba.cyanSoft },
  chipText: {
    fontFamily: brandTypography.body,
    fontSize: 10,
    fontWeight: '800',
    color: brandColors.ink,
  },
  pill: {
    height: 29,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexShrink: 0,
    alignSelf: 'flex-start',
  },
  pillDot: { width: 7, height: 7, borderRadius: 4 },
  pillText: { fontFamily: brandTypography.body, fontSize: 12, fontWeight: '800' },
  resourceRight: { flexDirection: 'column', alignItems: 'flex-end', gap: 8, flexShrink: 0 },
  configBtn: {
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: brandRgba.ink08,
    alignItems: 'center',
    justifyContent: 'center',
  },
  configBtnText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.ink,
  },
  composerHint: {
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 4,
    backgroundColor: brandRgba.cyanSoft,
    borderWidth: 1,
    borderColor: brandColors.cyan,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 54,
  },
  composerHintInfo: { backgroundColor: brandRgba.sageSoft, borderColor: brandColors.sage },
  composerBody: { flex: 1, gap: 3 },
  composerTitle: {
    fontFamily: brandTypography.body,
    fontSize: 15,
    fontWeight: '800',
    color: brandColors.ink,
  },
  composerSub: {
    fontFamily: brandTypography.body,
    fontSize: 12,
    fontWeight: '600',
    color: brandColors.textSoft,
  },
  composerBtn: {
    height: 38,
    paddingHorizontal: 16,
    borderRadius: 19,
    backgroundColor: brandColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  composerBtnText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    fontWeight: '800',
    color: brandColors.white,
  },
  settingsPanel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: brandColors.silver,
    backgroundColor: brandRgba.white88,
    padding: 14,
    gap: 6,
  },
  settingsLabel: {
    fontFamily: brandTypography.body,
    fontSize: 11,
    fontWeight: '800',
    color: brandColors.textMuted,
    marginTop: 6,
  },
  settingsValue: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    lineHeight: 18,
    color: brandColors.ink,
  },
  emptyText: {
    fontFamily: brandTypography.body,
    fontSize: 13,
    color: brandColors.textSoft,
    textAlign: 'center',
    paddingVertical: 18,
  },
});
