import { StyleSheet } from 'react-native';
import {
  brandColors,
  brandRgba,
  brandShadow,
  brandTypography,
  strongBrandShadow,
} from '@/theme/brandRefresh';

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.cream },
  content: { paddingHorizontal: 16, paddingBottom: 126 },
  header: {
    minHeight: 108,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandBlock: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 0 },
  brandMascot: { width: 60, height: 60, marginLeft: -8, marginRight: 6 },
  brandCopy: { flex: 1, minWidth: 0 },
  brandName: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
    color: brandColors.ink,
  },
  pageTitle: {
    fontFamily: brandTypography.display,
    fontSize: 46,
    lineHeight: 48,
    fontWeight: '900',
    color: brandColors.ink,
  },
  headerActions: { flexDirection: 'row', gap: 12, marginLeft: 10 },
  roundButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...brandShadow,
  },
  heroCard: {
    minHeight: 334,
    borderRadius: 28,
    backgroundColor: brandRgba.cyanWash,
    padding: 24,
    overflow: 'hidden',
    ...strongBrandShadow,
  },
  heroCopy: { width: '56%', zIndex: 2 },
  heroTitle: {
    fontFamily: brandTypography.display,
    fontSize: 32,
    lineHeight: 36,
    fontWeight: '900',
    color: brandColors.ink,
  },
  heroText: {
    marginTop: 12,
    fontFamily: 'Inter',
    fontSize: 15,
    lineHeight: 22,
    color: brandColors.textSoft,
  },
  connectionChip: {
    marginTop: 12,
    minHeight: 34,
    borderRadius: 17,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
  },
  connectionDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: brandColors.cyan },
  connectionText: { flex: 1, fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft },
  heroMascot: { position: 'absolute', right: -4, top: 22, width: 204, height: 204 },
  statsCard: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 18,
    minHeight: 84,
    borderRadius: 22,
    backgroundColor: brandRgba.white88,
    flexDirection: 'row',
    alignItems: 'stretch',
    overflow: 'hidden',
  },
  statCell: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  statCellBorder: { borderLeftWidth: 1, borderLeftColor: brandColors.silver },
  statIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  statBang: { fontFamily: 'Inter', fontSize: 20, fontWeight: '900', color: brandColors.white },
  statCheck: { fontFamily: 'Inter', fontSize: 20, fontWeight: '900', color: brandColors.white },
  statValue: {
    fontFamily: brandTypography.display,
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
    color: brandColors.ink,
  },
  statLabel: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft },
  searchSection: { marginTop: 24, flexDirection: 'row', alignItems: 'center', gap: 12 },
  searchBox: {
    flex: 1,
    height: 56,
    borderRadius: 28,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
  },
  searchInput: { flex: 1, fontFamily: 'Inter', fontSize: 17, color: brandColors.ink, padding: 0 },
  filterButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeader: {
    marginTop: 24,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: brandTypography.display,
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '900',
    color: brandColors.ink,
  },
  viewAll: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  viewAllText: { fontFamily: 'Inter', fontSize: 15, color: brandColors.textSoft },
  projectGroup: {
    borderRadius: 22,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    overflow: 'hidden',
    ...brandShadow,
  },
  projectItem: { width: '100%' },
  rowDivider: { height: 1, backgroundColor: brandRgba.silver78, marginLeft: 76 },
  workflowGrid: { flexDirection: 'row', gap: 14 },
  workflowCard: {
    flex: 1,
    minHeight: 88,
    borderRadius: 20,
    backgroundColor: brandRgba.cyanSoft,
    borderWidth: 1,
    borderColor: brandRgba.silver78,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  workflowImage: { width: 56, height: 56, marginRight: 8 },
  workflowCopy: { flex: 1, minWidth: 0 },
  workflowTitle: { fontFamily: 'Inter', fontSize: 15, fontWeight: '800', color: brandColors.ink },
  workflowSubtitle: {
    marginTop: 4,
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.textSoft,
  },
  workflowArrow: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: brandRgba.cyanWash,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  loadingText: { fontFamily: 'Inter', fontSize: 14, color: brandColors.textSoft },
  errorIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: brandRgba.white88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTitle: {
    fontFamily: brandTypography.display,
    fontSize: 24,
    fontWeight: '800',
    color: brandColors.error,
  },
  errorDesc: {
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.textSoft,
    textAlign: 'center',
    maxWidth: 260,
  },
  retryBtn: {
    height: 44,
    paddingHorizontal: 24,
    borderRadius: 22,
    backgroundColor: brandColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: { fontFamily: 'Inter', fontSize: 14, fontWeight: '700', color: brandColors.white },
  emptyWrap: {
    minHeight: 270,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyImage: { width: 108, height: 108 },
  emptyTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    fontWeight: '900',
    color: brandColors.ink,
  },
  emptyDesc: {
    fontFamily: 'Inter',
    fontSize: 15,
    lineHeight: 22,
    color: brandColors.textSoft,
    textAlign: 'center',
    maxWidth: 280,
  },
});
