import { StyleSheet } from 'react-native';
import {
  brandColors,
  brandRgba,
  brandShadow,
  brandTypography,
  strongBrandShadow,
} from '@/theme/brandRefresh';

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.cream },
  content: { paddingHorizontal: 16, paddingBottom: 96 },
  header: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandBlock: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 0 },
  brandMascot: { width: 46, height: 46, marginLeft: -6, marginRight: 6 },
  brandCopy: { minWidth: 0 },
  brandName: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
    color: brandColors.ink,
  },
  pageTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '700',
    color: brandColors.ink,
  },
  headerActions: { flexDirection: 'row', gap: 8, marginLeft: 8 },
  roundButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...brandShadow,
  },
  heroCard: {
    height: 226,
    borderRadius: 22,
    backgroundColor: brandColors.agentsHeroBlue,
    padding: 16,
    overflow: 'hidden',
    ...strongBrandShadow,
  },
  heroOrbit: {
    position: 'absolute',
    left: '49%',
    top: 42,
    width: 94,
    height: 94,
    borderRadius: 47,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: brandRgba.white70,
    transform: [{ rotate: '28deg' }],
  },
  heroSparkle: { position: 'absolute', left: '58%', top: 58, zIndex: 1 },
  heroCopy: { width: '57%', zIndex: 2 },
  heroTitle: {
    fontFamily: brandTypography.display,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: brandColors.ink,
  },
  heroText: {
    marginTop: 6,
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.textSoft,
  },
  connectionChip: {
    marginTop: 7,
    height: 26,
    maxWidth: 184,
    borderRadius: 13,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    gap: 6,
  },
  connectionDot: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: brandColors.cyan },
  connectionText: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 10,
    lineHeight: 14,
    color: brandColors.textSoft,
  },
  heroMascot: { position: 'absolute', right: 0, top: 24, width: 142, height: 138 },
  statsCard: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 12,
    height: 60,
    borderRadius: 16,
    backgroundColor: brandRgba.white88,
    flexDirection: 'row',
    alignItems: 'stretch',
    overflow: 'hidden',
  },
  statCell: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 5 },
  statCellBorder: { borderLeftWidth: 1, borderLeftColor: brandColors.silver },
  statIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 1,
  },
  statBang: { fontFamily: 'Inter', fontSize: 13, fontWeight: '900', color: brandColors.white },
  statCheck: { fontFamily: 'Inter', fontSize: 13, fontWeight: '900', color: brandColors.white },
  statValue: {
    fontFamily: brandTypography.display,
    fontSize: 17,
    lineHeight: 19,
    fontWeight: '900',
    color: brandColors.ink,
  },
  statLabel: { fontFamily: 'Inter', fontSize: 9, lineHeight: 11, color: brandColors.textSoft },
  searchSection: { marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 9 },
  searchBox: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 13,
  },
  searchInput: { flex: 1, fontFamily: 'Inter', fontSize: 14, color: brandColors.ink, padding: 0 },
  filterButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: brandRgba.white70,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonActive: {
    backgroundColor: brandColors.lime,
    borderColor: brandColors.ink,
  },
  filterDot: {
    position: 'absolute',
    right: 9,
    top: 9,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: brandColors.coral,
  },
  filterSummary: {
    marginTop: 8,
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 5,
    gap: 8,
  },
  filterSummaryText: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: brandColors.ink,
  },
  filterClearButton: {
    minHeight: 24,
    borderRadius: 12,
    backgroundColor: brandRgba.ink08,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterClearText: {
    fontFamily: 'Inter',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: brandColors.textSoft,
  },
  sectionHeader: {
    marginTop: 14,
    marginBottom: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: brandTypography.display,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '700',
    color: brandColors.ink,
  },
  viewAll: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  viewAllText: { fontFamily: 'Inter', fontSize: 13, color: brandColors.textSoft },
  projectGroup: {
    gap: 6,
  },
  fleetLoadingCard: {
    minHeight: 148,
    borderRadius: 22,
    backgroundColor: brandRgba.white88,
    borderWidth: 1,
    borderColor: brandColors.silver,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingVertical: 28,
    ...brandShadow,
  },
  workflowGrid: { gap: 8 },
  workflowCard: {
    width: '100%',
    minHeight: 58,
    borderRadius: 16,
    backgroundColor: brandRgba.cyanSoft,
    borderWidth: 1,
    borderColor: brandRgba.silver78,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    paddingHorizontal: 10,
    gap: 8,
  },
  workflowImage: { width: 34, height: 34, flexShrink: 0 },
  workflowCopy: { flex: 1, minWidth: 0 },
  workflowTitle: {
    fontFamily: 'Inter',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '800',
    color: brandColors.ink,
  },
  workflowSubtitle: {
    marginTop: 2,
    fontFamily: 'Inter',
    fontSize: 11,
    lineHeight: 14,
    color: brandColors.textSoft,
  },
  workflowArrow: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: brandRgba.cyanWash,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  loadingText: { fontFamily: 'Inter', fontSize: 14, color: brandColors.textSoft },
  errorIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: brandRgba.white88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '700',
    color: brandColors.error,
  },
  errorDesc: {
    fontFamily: 'Inter',
    fontSize: 13,
    color: brandColors.textSoft,
    textAlign: 'center',
    maxWidth: 260,
  },
  retryBtn: {
    height: 44,
    paddingHorizontal: 24,
    borderRadius: 22,
    backgroundColor: brandColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: { fontFamily: 'Inter', fontSize: 14, fontWeight: '700', color: brandColors.white },
  emptyWrap: {
    minHeight: 270,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyImage: { width: 108, height: 108 },
  emptyTitle: {
    fontFamily: brandTypography.display,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '700',
    color: brandColors.ink,
  },
  emptyDesc: {
    fontFamily: 'Inter',
    fontSize: 15,
    lineHeight: 22,
    color: brandColors.textSoft,
    textAlign: 'center',
    maxWidth: 280,
  },
  emptyBtn: {
    marginTop: 8,
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 26,
    backgroundColor: brandColors.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyBtnText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
    color: brandColors.white,
  },
});
